highlighter: pygments
safe: true
lsi: false
permalink: /:categories/:year-:month-:day-:title.html
markdown: kramdown
exclude: 
  - README.textile
  - import.rb
  - post.html
  - s3
  - lib
  - Rakefile
  - config.yaml
  - Gemfile
  - Gemfile.lock
